name: Sigma Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment‌‌
        run: |
          cd $GITHUB_WORKSPACE
          sudo apt remove firefox
          sudo apt autoremove
          sudo apt-get update && sudo apt-get upgrade -y
          sudo apt-get install git ccache automake flex lzop bison gperf build-essential zip curl zlib1g-dev g++-multilib libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng maven libssl-dev pwgen libswitch-perl policycoreutils minicom libxml-sax-base-perl libxml-simple-perl bc libc6-dev-i386 libx11-dev lib32z-dev libgl1-mesa-dev xsltproc unzip device-tree-compiler python3 -y
      - name: Build Kernel
        run: |
          cd $GITHUB_WORKSPACE
          sudo bash build.sh
          sudo chmod -R 0777 ./*

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ github.workspace }}/out/*
          name: Kernel-${{ github.run_id }}
          tag_name: ${{ github.run_id }}
          body: |
            Always Mewing
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
